// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Driven ports this context needs. Implemented by packages/adapters/*,
// wired in apps/core-api. Never imported by domain/.
import type { IdentityAccessAggregate } from "../../domain/index.js";

export interface IdentityAccessRepository {
  load(id: string): Promise<IdentityAccessAggregate | null>;
}

export interface RateLimiter {
  readonly __port: "RateLimiter";
}
