// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single OutboxWriter implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { OutboxWriter } from "@platos/kernel";

export interface OutboxAdapter extends OutboxWriter {
  readonly adapterName: "outbox";
}
