// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { AgentsRepository } from "./ports/index.js";
import type { TenancyContract } from "@platos/context-tenancy";
import type { ProvidersContract } from "@platos/context-providers";
import type { SkillsContract } from "@platos/context-skills";

export interface AgentsUseCases {
  readonly repository: AgentsRepository;
  readonly tenancy: TenancyContract;
  readonly providers: ProvidersContract;
  readonly skills: SkillsContract;
}
