// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { MemoryRepository } from "./ports/index.js";
import type { TenancyContract } from "@platos/context-tenancy";
import type { ProvidersContract } from "@platos/context-providers";

export interface MemoryUseCases {
  readonly repository: MemoryRepository;
  readonly tenancy: TenancyContract;
  readonly providers: ProvidersContract;
}
