// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { PrivacyAggregate } from "../domain/index.js";

export interface PrivacyContract {
  readonly name: "privacy";
  describe(id: string): Promise<PrivacyAggregate | null>;
}
