// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single RateLimiter implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { RateLimiter } from "@platos/kernel";

export interface RedisRatelimitAdapter extends RateLimiter {
  readonly adapterName: "redis-ratelimit";
}
