// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Process entry point. Boots the composition root and nothing else.
import type { AppModule } from "./app.module.js";

export type Bootstrap = () => Promise<AppModule>;
