// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { CostMonitoringAggregate } from "../domain/index.js";

export interface CostMonitoringContract {
  readonly name: "cost-monitoring";
  describe(id: string): Promise<CostMonitoringAggregate | null>;
}
