// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { ChannelsAggregate } from "../domain/index.js";

export interface ChannelsContract {
  readonly name: "channels";
  describe(id: string): Promise<ChannelsAggregate | null>;
}
