packages:
  - "packages/*"
  - "internal-packages/*"
  - "apps/**"
  - "docs"
  - "!packages/cli-v3/e2e/**"

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@trigger.dev/platform"
  - "next"
  - "@next/*"
  - "agentcrumbs"
  - "ai"
  - "@ai-sdk/*"
preferOffline: true

linkWorkspacePackages: false
publicHoistPattern:
  - "*prisma*"
preferWorkspacePackages: true
sideEffectsCache: false
