// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Thin bff transport. Calls context use-cases only.
import type { AppModule } from "../../app.module.js";

export interface BffTransport {
  readonly kind: "bff";
  readonly app: AppModule;
}
