// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { ProvidersAggregate } from "../domain/index.js";

export interface ProvidersContract {
  readonly name: "providers";
  describe(id: string): Promise<ProvidersAggregate | null>;
}
