// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { MemoryAggregate } from "../domain/index.js";

export interface MemoryContract {
  readonly name: "memory";
  describe(id: string): Promise<MemoryAggregate | null>;
}
