// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { EventingAggregate } from "../domain/index.js";

export interface EventingContract {
  readonly name: "eventing";
  describe(id: string): Promise<EventingAggregate | null>;
}
