// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { FilesAggregate } from "../domain/index.js";

export interface FilesContract {
  readonly name: "files";
  describe(id: string): Promise<FilesAggregate | null>;
}
