// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { JobsAggregate } from "../domain/index.js";

export interface JobsContract {
  readonly name: "jobs";
  describe(id: string): Promise<JobsAggregate | null>;
}
