import { Form, Link, useFetcher, useSearchParams } from "@remix-run/react";
import {
  asArray,
  asBoolean,
  asNumber,
  asRecord,
  asString,
  compactNumber,
  firstArray,
  moneyFromCents,
  percent,
  stableJson,
} from "../safe";
import {
  Alert,
  Button,
  CodeBlock,
  CollectionSearch,
  DataTable,
  EmptyState,
  FilterChip,
  Panel,
  PaginationRange,
  ProgressBar,
  SectionHeader,
  StatTile,
  StatusChip,
  Toolbar,
} from "../ProductPrimitives";
import { fieldClass, Status, type SurfaceProps } from "./SurfaceCommon";

function identityTone(index: number) {
  return ["var(--agent-indigo)", "var(--agent-violet)", "var(--agent-rose)", "var(--agent-amber)", "var(--agent-emerald)", "var(--agent-sky)", "var(--agent-teal)"][index % 7];
}

export function AgentsSurface({ data }: SurfaceProps) {
  const root = asRecord(data);
  const agents = firstArray(root, "agents", "items", "data");
  const [searchParams] = useSearchParams();
  const filter = searchParams.get("status") ?? "all";
  const total = asNumber(asRecord(root.pagination).total, asNumber(root.total, agents.length));
  const state = (agent: Record<string, unknown>) => {
    if (agent.isActive === false) return "paused";
    const health = asString(agent.health, asString(agent.status, "healthy")).toLowerCase();
    return ["broken", "failed", "disconnected", "unavailable"].includes(health) ? "broken" : "healthy";
  };
  const broken = agents.filter((value) => state(asRecord(value)) === "broken").length;
  if (!agents.length && total === 0 && !searchParams.get("search") && filter === "all") return <EmptyState title="No agents yet" description="An Agent is a configured AI worker: a model, prompt blocks, and the Tools it may call. Start with the minimum and verify the first successful Turn." action={<Link className="inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-white" to="new">Create your first agent</Link>} />;
  return <div className="space-y-4">
    {broken > 0 && <Alert tone="danger" title={`${broken} Agent${broken === 1 ? " is" : "s are"} broken on this page`}>The table marks runtime-unavailable Agents from canonical health or status fields. Open the Agent before changing configuration.</Alert>}
    <Toolbar><CollectionSearch placeholder="Search all Agents" /><div className="flex flex-wrap gap-2">{[["all", "All"], ["active", "Active"], ["paused", "Paused"]].map(([value, label]) => { const params = new URLSearchParams(searchParams); params.delete("page"); if (value === "all") params.delete("status"); else params.set("status", value); return <Link key={value} to={`?${params}`}><FilterChip active={filter === value}>{label}</FilterChip></Link>; })}</div><div className="ml-auto flex gap-2"><Link to="new"><Button type="button" tone="primary">New Agent</Button></Link></div></Toolbar>
    <DataTable headers={["Agent", "Runtime", "Model route", "Tool health", "Threads · 24h", "Cost · 7d", "Last active"]} rowKeys={agents.map((value) => asString(asRecord(value).id))} rows={agents.map((value, index) => {
      const agent = asRecord(value); const tools = asRecord(agent.toolsBlockConfig); const counts = asRecord(agent._count); const id = asString(agent.id); const currentState = state(agent); const toolBroken = asNumber(agent.brokenToolCount, asNumber(tools.brokenCount));
      return [<div className={`border-l-2 pl-3 ${currentState === "broken" ? "border-[var(--danger)]" : "border-transparent"}`}><Link className="flex items-center gap-2 font-medium text-[var(--accent)] hover:underline" to={id}><span className="grid h-7 w-7 place-items-center rounded-full text-xs font-semibold text-white" style={{ background: identityTone(index) }}>{asString(agent.name, agent.slug as string).slice(0, 2).toUpperCase()}</span>{asString(agent.name, agent.slug as string)}</Link><code className="mt-1 block text-[10px] text-text-dimmed">{id}</code></div>, <Status value={currentState} />, <div><code className="text-xs">{asString(agent.model, asString(asRecord(agent.defaultModelRoute).model, "Unresolved"))}</code><div className="mt-1 text-[11px] text-text-dimmed">{asString(agent.executionMode, "direct")} · {asString(tools.toolExposure, "meta")}</div></div>, <StatusChip tone={toolBroken > 0 ? "danger" : "good"}>{toolBroken > 0 ? `${toolBroken} broken` : asString(agent.toolHealth, "Ready")}</StatusChip>, compactNumber(agent.threads24h ?? counts.threads ?? agent.threadCount), moneyFromCents(agent.cost7dCents), asString(agent.lastActiveAt, asString(agent.updatedAt, "Never"))];
    })} />
    {!agents.length && <EmptyState title={total > 0 ? "No Agents on this page" : "No matching Agents"} description={total > 0 ? "This page is past the end of the Agent list. Use Previous to return to available results." : "No Agent in the complete scoped dataset matches the current server-side search and state filters."} />}
    <PaginationRange data={root} label="Agent pagination" />
  </div>;
}

export function AgentConfigSurface({ data, secondary, title }: SurfaceProps) {
  const create = title.toLowerCase().includes("create");
  const source = asRecord(data);
  const providers = create ? firstArray(source, "providers") : [];
  const promptDefaults = create ? firstArray(asRecord(secondary), "blocks") : [];
  const readyProviders = providers.filter((value) => { const provider = asRecord(value); return asBoolean(provider.linked) && asBoolean(provider.enabled) && asBoolean(provider.envReady) && asArray(provider.models).length > 0; });
  const defaultModel = asArray(asRecord(readyProviders[0]).models).map((value) => asString(value)).find(Boolean) ?? "";
  const agent = create ? {
    model: defaultModel,
    modelRoutes: defaultModel ? [{ label: "default", model: defaultModel, isDefault: true }] : [],
    promptBlocks: promptDefaults,
  } : source;
  const tools = asRecord(agent.toolsBlockConfig); const routes = asArray(agent.modelRoutes); const promptBlocks = asArray(agent.promptBlocks);
  const defaultRoutes = routes;
  const mutation = useFetcher<{ ok: boolean; result?: { id?: string }; error?: string }>();
  return <mutation.Form method="post" className="space-y-5">
    {create && <><div className="grid gap-3 md:grid-cols-3"><StatTile title="Provider readiness" value={`${readyProviders.length} ready`} hint={`${providers.length} canonical providers`} /><StatTile title="Default model" value={<code className="text-xs">{defaultModel || "Unresolved"}</code>} /><StatTile title="Prompt defaults" value={promptDefaults.length ? `${promptDefaults.length} blocks` : "Unavailable"} /></div>{!defaultModel && <Alert tone="warning" title="No canonical provider default is ready">Enable and configure a provider before creating an Agent. The form will not invent a provider or model.</Alert>}<Panel><SectionHeader title="Canonical provider readiness" description="Provider metadata and prompt defaults are readiness inputs, not an Agent record." /><DataTable headers={["Provider", "Linked", "Enabled", "Credentials", "Models"]} rows={providers.map((value) => { const provider = asRecord(value); return [asString(provider.displayName, asString(provider.id)), <Status value={asBoolean(provider.linked) ? "linked" : "unlinked"} />, <Status value={asBoolean(provider.enabled) ? "enabled" : "disabled"} />, <Status value={asBoolean(provider.envReady) ? "ready" : "missing"} />, asArray(provider.models).length]; })} empty={<EmptyState title="No provider readiness" description="The canonical provider endpoint returned no provider metadata." />} /></Panel></>}
    <Panel><SectionHeader title="Identity and runtime" description="Typed fields persist into a new immutable AgentVersion." /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs">Name<input required={create} name="name" defaultValue={asString(agent.name, create ? "support-agent" : "")} className={fieldClass} /></label>{create && <label className="text-xs">Slug<input name="slug" defaultValue="support-agent" className={fieldClass} /></label>}<label className="text-xs">Primary model<input required name="model" defaultValue={asString(agent.model, "")} className={`${fieldClass} font-mono`} /></label><label className="text-xs">Execution<select name="executionMode" defaultValue={asString(agent.executionMode, "direct")} className={fieldClass}><option value="direct">Direct execution</option><option value="durable">Durable execution</option></select></label><label className="text-xs">Guest visibility<select name="visibility" defaultValue={asString(agent.visibility, "private")} className={fieldClass}><option value="private">Private</option><option value="public-guest">Public guest</option></select></label></div></Panel>
    <Panel><SectionHeader title="Prompt blocks" description="Ordered runtime prompt composition. Volatile variables belong below the cache boundary." />{promptBlocks.length ? <div className="space-y-2">{promptBlocks.map((value, index) => { const block = asRecord(value); return <article key={index} className="rounded-md border border-grid-bright bg-[var(--surface-2)] p-3"><div className="flex items-center justify-between gap-3"><div><span className="font-mono text-[10px] text-text-dimmed">{String(index + 1).padStart(2, "0")}</span><span className="ml-2 text-sm font-medium">{asString(block.label, asString(block.type, `Block ${index + 1}`))}</span></div><StatusChip tone={asBoolean(block.volatile) ? "warning" : "accent"}>{asBoolean(block.volatile) ? "volatile" : "cached prefix"}</StatusChip></div><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-xs text-text-dimmed">{asString(block.content, asString(block.prompt, "Structured block"))}</p></article>; })}<div className="my-3 flex items-center gap-3 text-[10px] uppercase tracking-widest text-[var(--warn)]"><span className="h-px flex-1 bg-[var(--warn)]" />Cache boundary<span className="h-px flex-1 bg-[var(--warn)]" /></div></div> : <EmptyState title="No prompt blocks" description="The system prompt remains the only prompt input until structured blocks are added." />}
      <label className="mt-4 block text-xs">System prompt<textarea name="systemPrompt" defaultValue={asString(agent.systemPrompt, "")} className={`${fieldClass} min-h-32`} /></label>
      <details className="mt-4"><summary className="cursor-pointer text-xs font-medium text-[var(--accent)]">Advanced structured prompt JSON</summary><textarea name="promptBlocks" defaultValue={stableJson(promptBlocks)} className={`${fieldClass} min-h-44 font-mono text-xs`} /></details>
    </Panel>
    <Panel><SectionHeader title="Model and routes" description="The runtime resolves exactly one default route; unresolved provider credentials remain explicit." /><div className="grid gap-3 lg:grid-cols-2">{defaultRoutes.map((value, index) => { const route = asRecord(value); return <div key={index} className="rounded-md border border-grid-bright p-3"><div className="flex items-center justify-between"><span className="font-medium">{asString(route.label, `Route ${index + 1}`)}</span>{asBoolean(route.isDefault) && <StatusChip tone="accent">default</StatusChip>}</div><code className="mt-2 block text-xs">{asString(route.model, "Unresolved model")}</code><p className="mt-2 text-[11px] text-text-dimmed">Provider key: {asString(route.providerKeyId, "Environment default")}</p></div>; })}</div><details className="mt-4"><summary className="cursor-pointer text-xs font-medium text-[var(--accent)]">Advanced model route JSON</summary><textarea name="modelRoutes" defaultValue={stableJson(defaultRoutes)} className={`${fieldClass} min-h-44 font-mono text-xs`} /></details></Panel>
    <Panel><SectionHeader title="Tools, memory and limits" /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs">Tool caller<select name="toolMode" defaultValue={asString(tools.mode, asString(agent.toolMode, "direct"))} className={fieldClass}><option value="direct">Parent Agent</option><option value="sub-agent">Sub-agent</option><option value="execute-tool">execute_tools</option></select></label><label className="text-xs">Tool exposure<select name="toolExposure" defaultValue={asString(tools.toolExposure, "meta")} className={fieldClass}><option value="direct">Direct schemas</option><option value="meta">Meta router</option></select></label><label className="text-xs">History<select name="historyMode" defaultValue={asString(agent.historyMode, "rolling")} className={fieldClass}><option value="rolling">Rolling</option><option value="compact">Compact</option></select></label><label className="text-xs">Max steps<input type="number" name="maxSteps" min="1" max="200" defaultValue={asNumber(agent.maxSteps, 20)} className={fieldClass} /></label><label className="text-xs">Context limit<input type="number" name="contextLimit" min="1" max="500" defaultValue={asNumber(agent.contextLimit, 20)} className={fieldClass} /></label><label className="text-xs">Compact threshold<input type="number" name="compactThreshold" min="1" max="100" defaultValue={asNumber(agent.compactThreshold, 40)} className={fieldClass} /></label></div></Panel>
    {!create && <label className="block text-xs">Version note<input name="versionNote" placeholder="Why this runtime configuration changed" className={fieldClass} /></label>}<Button type="submit" tone="primary" disabled={mutation.state !== "idle" || (create && !defaultModel)}>{mutation.state === "idle" ? (create ? "Create Agent" : "Save as immutable version") : "Saving…"}</Button>
    {mutation.data && <Alert tone={mutation.data.ok ? "good" : "danger"} title={mutation.data.ok ? (create ? "Agent created" : "Immutable version saved") : "Operation failed"}>{mutation.data.ok ? (mutation.data.result?.id ? `Persisted Agent ${mutation.data.result.id}.` : "Mutation persisted through the canonical API.") : mutation.data.error || "Agent configuration failed"}</Alert>}
  </mutation.Form>;
}

export function AgentContextSurface({ data }: SurfaceProps) {
  const agent = asRecord(data); const mapping = asRecord(agent.contextMapping); const promptVars = asArray(mapping.promptVars).filter((value): value is string => typeof value === "string"); const declared = asArray(mapping.declaredKeys).filter((value): value is string => typeof value === "string"); const prompt = `${asString(agent.systemPrompt)} ${stableJson(agent.promptBlocks)}`; const placeholders = [...new Set(Array.from(prompt.matchAll(/\{\{\s*([a-zA-Z_][a-zA-Z0-9_.]*)\s*\}\}/g), (match) => match[1]))]; const configured = [...new Set([...promptVars, ...placeholders])]; const volatile = configured.filter((key) => key === "user.current_time"); const cached = configured.filter((key) => !volatile.includes(key)); const unresolved = placeholders.filter((key) => !declared.includes(key) && !volatile.includes(key));
  const variables = (items: string[]) => items.length ? <div className="flex flex-wrap gap-2">{items.map((item) => <code key={item} className="rounded-full border border-grid-bright bg-[var(--surface-2)] px-2 py-1 text-xs">{item}</code>)}</div> : <p className="text-sm text-text-dimmed">None configured</p>;
  return <div className="grid gap-4 lg:grid-cols-3"><Panel><SectionHeader title="Cached variables" description="Stable values can remain before the cache boundary." />{variables(cached)}</Panel><Panel tone="accent"><SectionHeader title="Volatile variables" description="Relocated after the final cache breakpoint on every Turn." />{variables(volatile)}</Panel><Panel tone={unresolved.length ? "warning" : "default"}><SectionHeader title="Unresolved" description="Caller-owned placeholders missing from the declared contract." />{variables(unresolved)}</Panel><Panel className="lg:col-span-3"><SectionHeader title="Effective Context mapping" description="Canonical runtime-readable mapping; no values are inferred by the dashboard." /><CodeBlock>{stableJson(mapping)}</CodeBlock></Panel></div>;
}

export function AgentToolsSurface({ data }: SurfaceProps) {
  const root = asRecord(data); const rows = firstArray(root, "tools", "rows"); const exposure = asString(root.toolExposure, "meta"); const broken = rows.filter((value) => !asBoolean(asRecord(value).dispatchable)).length; const total = asNumber(asRecord(root.pagination).total, rows.length); const [searchParams] = useSearchParams();
  return <div className="space-y-4"><Toolbar><CollectionSearch label="Search Agent Tools" placeholder="Search all Agent Tools" /></Toolbar>{broken > 0 && <Alert tone="danger" title={`${broken} Tool mapping${broken === 1 ? " is" : "s are"} not dispatchable on this page`}>Registry presence is not health. The rows below preserve the canonical executor state.</Alert>}<div className="grid gap-3 md:grid-cols-3"><StatTile title="Matching Entity Tools" value={total} /><StatTile title="Exposure" value={exposure === "direct" ? "Direct" : "Meta"} hint={exposure === "direct" ? "Enabled schemas injected" : "Enabled Tools remain find-only"} /><StatTile title="Runtime Tools" value="Always present" hint="Unaffected by Direct / Meta" /></div>{rows.length ? <DataTable headers={["Tool", "Source Entity", "Turn exposure", "Live state", "Mapping"]} rowKeys={rows.map((value, index) => { const row = asRecord(value); return `${asString(row.toolName, `tool-${index}`)}:${asString(row.sourceEntity)}`; })} rows={rows.map((value) => { const row = asRecord(value); const toolName = asString(row.toolName); const sourceEntity = asString(row.sourceEntity); const enabled = asBoolean(row.enabled); const turnExposure = !enabled ? "Disabled" : exposure === "direct" ? "Injected" : "Find-only"; return [<code>{toolName}</code>, <code className="text-xs">{sourceEntity}</code>, turnExposure, <div className="space-y-1"><Status value={asBoolean(row.dispatchable) ? "Dispatchable" : "Unavailable"} /><div className="text-xs text-text-dimmed">{asString(row.health, "unknown")}</div></div>, <Form method="post"><input type="hidden" name="toolId" value={asString(row.toolId)} /><input type="hidden" name="enabled" value={enabled ? "false" : "true"} /><button className="text-xs text-[var(--accent)] hover:underline">{enabled ? "Disable mapping" : "Enable mapping"}</button></Form>]; })} /> : <EmptyState title={total > 0 ? "No Agent Tools on this page" : searchParams.get("search") ? "No matching Agent Tools" : "No Tools exposed"} description={total > 0 ? "This page is past the end of the Agent Tool list. Use Previous to return to available results." : searchParams.get("search") ? "No Agent Tools match the current server-side search." : "Runtime Tools remain available; no Entity Tool mapping exists for this Agent."} />}<PaginationRange data={root} label="Agent Tool pagination" /><p className="text-xs text-text-dimmed">Mapping changes invalidate the canonical runtime cache, so the next Turn sees this same state.</p></div>;
}

export function CanarySurface({ data }: SurfaceProps) {
  const root = asRecord(data); const rows = firstArray(root, "perVersion"); const canaryId = asString(root.canaryVersionId, ""); const current = rows.find((value) => asBoolean(asRecord(value).isCurrent)); const canary = rows.find((value) => asBoolean(asRecord(value).isCanary)); const currentError = asNumber(asRecord(current).errorRate); const canaryError = asNumber(asRecord(canary).errorRate); const degraded = Boolean(canaryId && canaryError > currentError);
  return <div className="space-y-5">{degraded && <Alert tone="danger" title="Canary degradation detected">The endpoint reports a higher canary error rate than the active cohort. Review persisted cohort metrics before promotion.</Alert>}<div className="grid gap-3 md:grid-cols-3"><StatTile title="Active version" value={<code className="text-sm">{asString(root.currentVersionId, "—")}</code>} /><StatTile title="Canary version" value={<code className="text-sm">{canaryId || "Disabled"}</code>} /><StatTile title="Traffic" value={`${asNumber(root.canaryPercent)}%`} hint={`${asNumber(root.hours, 24)} hour persisted cohort window`} /></div><ProgressBar value={asNumber(root.canaryPercent)} label={`${asNumber(root.canaryPercent)}% canary · ${100 - asNumber(root.canaryPercent)}% active`} /><DataTable headers={["Version", "Cohort", "Turns", "Ledger cost", "Tokens", "Latency / errors"]} rows={rows.map((value) => { const row = asRecord(value); return [`v${asNumber(row.versionNumber) || "?"}`, <Status value={asBoolean(row.isCurrent) ? "stable" : asBoolean(row.isCanary) ? "canary" : "historical"} />, compactNumber(row.turnCount ?? row.tasks), moneyFromCents(row.totalCostCents), `${compactNumber(row.inputTokens)} in / ${compactNumber(row.outputTokens)} out`, `${compactNumber(row.avgLatencyMs)}ms / ${percent(row.errorRate)}`]; })} empty={<EmptyState title="No cohort metrics" description="No persisted Turn or Step cohort data exists for the selected window." />} /><div className="grid gap-4 lg:grid-cols-2"><Form method="post"><Panel><input type="hidden" name="intent" value="set" /><SectionHeader title="Set canary traffic" /><label className="text-xs">Immutable canary version ID<input name="canaryVersionId" defaultValue={canaryId} placeholder="Leave blank to disable canary" className={fieldClass} /></label><label className="mt-3 block text-xs">Percent<input type="number" name="canaryPercent" min="0" max="100" defaultValue={asNumber(root.canaryPercent)} className={fieldClass} /></label><Button type="submit" className="mt-3">Apply persisted cohort</Button></Panel></Form><Form method="post"><Panel><input type="hidden" name="intent" value="promote" /><SectionHeader title="Promote canary" description="Atomically makes the canary active and clears canary traffic. Promotion writes immutable audit metadata." /><Button type="submit" disabled={!canaryId} tone="primary">Promote to active</Button></Panel></Form></div></div>;
}

const versionFields = ["model", "systemPrompt", "executionMode", "toolsBlockConfig", "modelRoutes", "promptBlocks", "contextMapping"] as const;
function versionConfig(value: unknown) { const row = asRecord(value); const snapshot = asRecord(row.configSnapshot); return Object.keys(snapshot).length ? snapshot : Object.keys(asRecord(row.config)).length ? asRecord(row.config) : row; }
function diffLines(previous: unknown, next: unknown) { const before = stableJson(previous).split("\n"); const after = stableJson(next).split("\n"); const beforeSet = new Set(before); const afterSet = new Set(after); return { removed: before.filter((line) => !afterSet.has(line)), added: after.filter((line) => !beforeSet.has(line)) }; }
export function VersionsSurface({ data }: SurfaceProps) {
  const root = asRecord(data); const versions = firstArray(root, "versions", "items"); const newest = versionConfig(versions[0]); const previous = versionConfig(versions[1]); const changes = versionFields.filter((field) => stableJson(newest[field]) !== stableJson(previous[field]));
  if (!versions.length) { const total = asNumber(asRecord(root.pagination).total, asNumber(root.total)); return <><EmptyState title={total > 0 ? "No versions on this page" : "No versions"} description={total > 0 ? "This page is past the end of the version history. Use Previous to return to available results." : "Create or save an Agent configuration to produce the first immutable version."} /><PaginationRange data={root} label="Agent version pagination" /></>; }
  return <div><div className="grid gap-4 xl:grid-cols-[22rem_minmax(0,1fr)]"><DataTable headers={["Version", "State", "Note", "Action"]} rowKeys={versions.map((value) => asString(asRecord(value).id))} rows={versions.map((value) => { const version = asRecord(value); const id = asString(version.id); return [asNumber(version.versionNumber) ? `v${asNumber(version.versionNumber)}` : asString(version.label, id), <Status value={asBoolean(version.isCurrent) ? "current" : asBoolean(version.isCanary) ? "canary" : "historical"} />, asString(version.note, "—"), <Form method="post"><input type="hidden" name="versionId" value={id} /><button className="text-xs text-[var(--accent)] hover:underline">Roll back via new immutable version</button></Form>]; })} /><Panel><SectionHeader title="Semantic config diff" description="Newest versus previous versions on this page. Only changed runtime fields are shown." />{!changes.length ? <EmptyState title={versions.length === 1 ? "One version on this page" : "No field changes"} description="A second distinct immutable version on this page is required for comparison." /> : <div className="space-y-3">{changes.map((field) => { const diff = diffLines(previous[field], newest[field]); return <details key={field} className="rounded border border-grid-bright p-3" open><summary className="cursor-pointer font-medium">{field}</summary><div className="mt-3 grid gap-3 xl:grid-cols-2"><CodeBlock label="Removed"><span className="text-[var(--danger)]">{diff.removed.length ? diff.removed.map((line) => `- ${line}`).join("\n") : "No removed lines"}</span></CodeBlock><CodeBlock label="Added"><span className="text-[var(--good)]">{diff.added.length ? diff.added.map((line) => `+ ${line}`).join("\n") : "No added lines"}</span></CodeBlock></div></details>; })}</div>}</Panel></div><PaginationRange data={root} label="Agent version pagination" /></div>;
}
