// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { GovernanceAggregate } from "../domain/index.js";

export interface GovernanceContract {
  readonly name: "governance";
  describe(id: string): Promise<GovernanceAggregate | null>;
}
