export type ReferenceRouteClassification = {
  reference: string;
  classification: "production" | "approved-exclusion";
  target: string;
  rationale?: string;
};

export const referenceRouteManifest: ReferenceRouteClassification[] = [
  { reference: "00-index.dc.html", classification: "production", target: "/" },
  { reference: "01-auth.dc.html", classification: "production", target: "/login" },
  { reference: "02-onboarding.dc.html", classification: "production", target: "/orgs/new" },
  { reference: "03-home.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug" },
  { reference: "04-command.dc.html", classification: "production", target: "DashboardShell.GlobalSearchLauncher" },
  { reference: "05-orgs.dc.html", classification: "production", target: "/orgs/:organizationSlug" },
  { reference: "07-billing.dc.html", classification: "approved-exclusion", target: "unavailable", rationale: "No canonical billing endpoint exists; Cost and Budgets remain usage-ledger screens, not billing projections." },
  { reference: "08-account.dc.html", classification: "production", target: "/account" },
  { reference: "09-agent-share.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId/share" },
  { reference: "10-agents.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents" },
  { reference: "11-agent-new.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/new" },
  { reference: "12-agent-config.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId" },
  { reference: "13-agent-context.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId/context" },
  { reference: "14-agent-tools.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId/tools" },
  { reference: "15-agent-versions.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId/versions" },
  { reference: "16-threads.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/threads" },
  { reference: "17-thread.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/threads/:threadId" },
  { reference: "18-trace.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/threads/:threadId/trace" },
  { reference: "19-playground.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId/chat" },
  { reference: "20-entities.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-entities" },
  { reference: "21-entity.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-entities/:entityId" },
  { reference: "22-mcp.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/mcps" },
  { reference: "23-tools.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-tools" },
  { reference: "24-providers.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-providers" },
  { reference: "25-memory.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/memories" },
  { reference: "26-graph.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/memories/graph" },
  { reference: "27-clusters.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-clusters" },
  { reference: "28-skills.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/skills" },
  { reference: "29-monitoring.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-monitoring" },
  { reference: "30-cost.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/cost" },
  { reference: "31-budgets.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-budgets" },
  { reference: "32-traces.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/threads" },
  { reference: "34-approvals.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/approvals" },
  { reference: "35-governance.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-governance" },
  { reference: "36-evals.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-evals" },
  { reference: "37-audit.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/audit" },
  { reference: "38-jobs.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/platos-tasks" },
  { reference: "39-variables.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/environment-variables" },
  { reference: "40-settings.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/settings/general" },
  { reference: "41-widget.dc.html", classification: "production", target: "/embed/:agentId" },
  { reference: "42-connect.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agent-connect" },
  { reference: "43-docs.dc.html", classification: "approved-exclusion", target: "unavailable", rationale: "No canonical hosted docs capability exists in this repository." },
  { reference: "44-debug.dc.html", classification: "production", target: "/orgs/:organizationSlug/projects/:projectSlug/env/:environmentSlug/agents/:agentId/postman-templates" },
  { reference: "45-admin.dc.html", classification: "approved-exclusion", target: "unavailable", rationale: "No canonical product admin endpoint or authorization model exists." },
  { reference: "46-errors.dc.html", classification: "production", target: "root.ErrorBoundary" },
  { reference: "47-parts.dc.html", classification: "production", target: "ProductPrimitives" },
  { reference: "PlatosNav.dc.html", classification: "production", target: "DashboardShell.AppShell" },
];
