// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { ObservabilityAggregate } from "../domain/index.js";

export interface ObservabilityContract {
  readonly name: "observability";
  describe(id: string): Promise<ObservabilityAggregate | null>;
}
