/**
 * SESSION-BOUNDARY SCOPE — single source of truth for the scope fields that
 * must survive the Trigger-session boundary.
 *
 * A durable/session turn does NOT run on the original request scope. The
 * gateway/dispatch serializes a scope into the AgentChat `clientData`, the
 * Trigger worker forwards it, and the turn is reconstructed from it on the far
 * side (`chat-session.task.ts` → `POST /internal/chat/stream-turn`). Any field
 * NOT carried here silently vanishes on durable turns only — this is the bug
 * class behind a string of regressions that each looked unrelated:
 *   - `userToken`      dropped → entity tool calls failed `verifyTurnProof`
 *                      ("turn proof missing/invalid — rejecting").
 *   - `sessionContext` dropped → datetime block rendered server UTC and
 *                      `{{user.*}}` went empty (wrong-timezone bug).
 *   - `userIdentities` dropped → `resolveEndUser` had no channel claims, so
 *                      the end-user could not be linked on durable turns.
 *   - `principal`      dropped → trust tier defaulted to "end-user", so an
 *                      operator's durable turn lost operator surfaces.
 *
 * Rather than keep patching field-by-field, `buildSessionScope` is the ONE
 * place that decides what crosses. Add a field here (and to `SessionScope`)
 * and it flows end-to-end; forget one and it can't silently regress a single
 * hop, because every hop below is typed to `SessionScope`.
 *
 * DELIBERATELY EXCLUDED:
 *   - `traceId` / `parentSpanId` — per-turn OTel context, regenerated by
 *     AgentTaskService for the new turn; carrying stale values would corrupt
 *     the span tree.
 *   - `contextMapping` / `clusteringId` — recomputed in-turn from the thread
 *     row + agent config (not inbound request state).
 *   - `agentId` / `sessionId` / `threadId` — re-stamped during reconstruction.
 *
 * This module is intentionally dependency-free so Trigger task bundles can
 * `import type { SessionScope }` from it without pulling in Nest.
 */

/** Channel-native identity claim (subset of RequestScope.userIdentities item). */
export interface SessionIdentityClaim {
  channel: string;
  handle: string;
  verified?: boolean;
}

/**
 * The exact shape placed into AgentChat `clientData.scope`. A structural subset
 * of `RequestScope` — every field here also exists on `RequestScope`, so the
 * reconstructed object is assignable back to it.
 */
export interface SessionScope {
  organizationId: string;
  projectId: string;
  environmentId: string;
  userId: string;
  /** 120s per-user HMAC turn-proof — forwarded to entity tool calls. */
  userToken?: string;
  /** Minting-entity hint (Mode 2). */
  entityId?: string;
  /** Trust tier resolved by the original request's auth. Absent ⇒ end-user. */
  principal?: "operator" | "end-user";
  /** Channel identity claims for cross-channel end-user linking (non-guest only). */
  userIdentities?: SessionIdentityClaim[];
  /** Per-turn context (user_timezone, user.* identity, sessionContextOverride). */
  sessionContext?: Record<string, unknown>;
  /**
   * Plaintext identity an entity SIGNED for, resolved by the original request's
   * auth. Carried for the same reason `principal` is: it is decided once, at the
   * edge, and a durable turn has no way to re-derive it. Dropping it would leave
   * the analytical projection with no identity on durable turns only — the
   * quiet, one-hop-at-a-time regression this module exists to prevent.
   */
  signedUserMeta?: { name?: string; email?: string };
}

/** Structural input — anything with the RequestScope shape (avoids a Nest import). */
export interface SessionScopeInput {
  organizationId: string;
  projectId: string;
  environmentId: string;
  userId: string;
  userToken?: string;
  entityId?: string;
  principal?: "operator" | "end-user";
  userIdentities?: SessionIdentityClaim[];
  sessionContext?: Record<string, unknown> | null;
  signedUserMeta?: { name?: string; email?: string };
}

/**
 * Build the scope object that crosses the session boundary. Optional fields are
 * omitted when empty so the wire payload stays minimal and a `null`
 * sessionContext doesn't clobber the far side. NON-secret by contract: the
 * gateway strips secrets before anything reaches these fields; `userToken` is a
 * short-lived signed proof, not a durable credential.
 */
export function buildSessionScope(scope: SessionScopeInput): SessionScope {
  return {
    organizationId: scope.organizationId,
    projectId: scope.projectId,
    environmentId: scope.environmentId,
    userId: scope.userId,
    ...(scope.userToken ? { userToken: scope.userToken } : {}),
    ...(scope.entityId ? { entityId: scope.entityId } : {}),
    ...(scope.principal ? { principal: scope.principal } : {}),
    ...(scope.userIdentities && scope.userIdentities.length > 0
      ? { userIdentities: scope.userIdentities }
      : {}),
    ...(scope.sessionContext ? { sessionContext: scope.sessionContext } : {}),
    ...(scope.signedUserMeta && (scope.signedUserMeta.name || scope.signedUserMeta.email)
      ? { signedUserMeta: scope.signedUserMeta }
      : {}),
  };
}
