// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// ADR M0.3 §4 kernel-hosted decoupling ports. Declarations only.
export interface EventBus {
  readonly __port: "EventBus";
}

export interface OutboxWriter {
  readonly __port: "OutboxWriter";
}

export interface UnitOfWork {
  readonly __port: "UnitOfWork";
}

export interface Clock {
  readonly __port: "Clock";
}

export interface IdGenerator {
  readonly __port: "IdGenerator";
}

export interface Logger {
  readonly __port: "Logger";
}

export interface DurableRuntime {
  readonly __port: "DurableRuntime";
}

export interface SafetyEventSink {
  readonly __port: "SafetyEventSink";
}

export interface ErasureTarget {
  readonly __port: "ErasureTarget";
}
