// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Thin mcp transport. Calls context use-cases only.
import type { AppModule } from "../../app.module.js";

export interface McpTransport {
  readonly kind: "mcp";
  readonly app: AppModule;
}
