// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Driven ports this context needs. Implemented by packages/adapters/*,
// wired in apps/core-api. Never imported by domain/.
import type { MemoryAggregate } from "../../domain/index.js";

export interface MemoryRepository {
  load(id: string): Promise<MemoryAggregate | null>;
}
