// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// ADR M0.3 §4 pure value objects. Declarations only.
export interface TenantScope {
  readonly organizationId: string;
}

export interface RequestScope {
  readonly tenant: TenantScope;
  readonly requestId: string;
}

export interface Money {
  readonly cents: number;
  readonly currency: string;
}

export interface DomainEvent {
  readonly name: string;
  readonly occurredAt: string;
}
