// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single TenancyRepository implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { TenancyRepository } from "@platos/kernel";

export interface PostgresTenancyAdapter extends TenancyRepository {
  readonly adapterName: "postgres-tenancy";
}
