// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Thin ws transport. Calls context use-cases only.
import type { AppModule } from "../../app.module.js";

export interface WsTransport {
  readonly kind: "ws";
  readonly app: AppModule;
}
