// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { ConversationsAggregate } from "../domain/index.js";

export interface ConversationsContract {
  readonly name: "conversations";
  describe(id: string): Promise<ConversationsAggregate | null>;
}
