// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { SecretsRepository } from "./ports/index.js";

export interface SecretsUseCases {
  readonly repository: SecretsRepository;
}
