// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { ToolsRepository } from "./ports/index.js";
import type { TenancyContract } from "@platos/context-tenancy/contracts/index.js";
import type { IdentityAccessContract } from "@platos/context-identity-access/contracts/index.js";
import type { SecretsContract } from "@platos/context-secrets/contracts/index.js";
import type { ProvidersContract } from "@platos/context-providers/contracts/index.js";

export interface ToolsUseCases {
  readonly repository: ToolsRepository;
  readonly tenancy: TenancyContract;
  readonly identityAccess: IdentityAccessContract;
  readonly secrets: SecretsContract;
  readonly providers: ProvidersContract;
}
