// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Thin webhook transport. Calls context use-cases only.
import type { AppModule } from "../../app.module.js";

export interface WebhookTransport {
  readonly kind: "webhook";
  readonly app: AppModule;
}
