// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Thin channels-ingress transport. Calls context use-cases only.
import type { AppModule } from "../../app.module.js";

export interface ChannelsIngressTransport {
  readonly kind: "channels-ingress";
  readonly app: AppModule;
}
