// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single EventBus implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { EventBus } from "@platos/kernel";

export interface RedisStreamsAdapter extends EventBus {
  readonly adapterName: "redis-streams";
}
