// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single Notifier implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { Notifier } from "@platos/context-cost-monitoring/application/ports/index.js";

export interface NotifierEmailAdapter extends Notifier {
  readonly adapterName: "notifier-email";
}
