// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single DurableRuntime implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { DurableRuntime } from "@platos/kernel";

export interface DurableRuntimeAdapter extends DurableRuntime {
  readonly adapterName: "durable-runtime";
}
