// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Driven ports this context needs. Implemented by packages/adapters/*,
// wired in apps/core-api. Never imported by domain/.
import type { TenancyAggregate } from "../../domain/index.js";

export interface TenancyRepository {
  load(id: string): Promise<TenancyAggregate | null>;
}
