// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { AgentsAggregate } from "../domain/index.js";

export interface AgentsContract {
  readonly name: "agents";
  describe(id: string): Promise<AgentsAggregate | null>;
}
