// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single ChannelAdapter implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { ChannelAdapter } from "@platos/context-channels/application/ports/index.js";

export interface ChannelSlackAdapter extends ChannelAdapter {
  readonly adapterName: "channel-slack";
}
