// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single ObjectStore implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { ObjectStore } from "@platos/kernel";

export interface ObjectstoreMinioAdapter extends ObjectStore {
  readonly adapterName: "objectstore-minio";
}
