// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { TenancyRepository } from "./ports/index.js";
import type { IdentityAccessContract } from "@platos/context-identity-access";

export interface TenancyUseCases {
  readonly repository: TenancyRepository;
  readonly identityAccess: IdentityAccessContract;
}
