// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Pure domain. May import its own domain and @platos/kernel only.
import type { TenantScope } from "@platos/kernel";

export interface TenancyAggregate {
  readonly scope: TenantScope;
  readonly id: string;
}
