// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { TenancyAggregate } from "../domain/index.js";

export interface TenancyContract {
  readonly name: "tenancy";
  describe(id: string): Promise<TenancyAggregate | null>;
}
