// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { ConversationsRepository } from "./ports/index.js";
import type { AgentsContract } from "@platos/context-agents";
import type { SkillsContract } from "@platos/context-skills";
import type { ToolsContract } from "@platos/context-tools";
import type { MemoryContract } from "@platos/context-memory";
import type { ProvidersContract } from "@platos/context-providers";
import type { FilesContract } from "@platos/context-files";
import type { CostMonitoringContract } from "@platos/context-cost-monitoring";
import type { JobsContract } from "@platos/context-jobs";
import type { SecretsContract } from "@platos/context-secrets";
import type { TenancyContract } from "@platos/context-tenancy";

export interface ConversationsUseCases {
  readonly repository: ConversationsRepository;
  readonly agents: AgentsContract;
  readonly skills: SkillsContract;
  readonly tools: ToolsContract;
  readonly memory: MemoryContract;
  readonly providers: ProvidersContract;
  readonly files: FilesContract;
  readonly costMonitoring: CostMonitoringContract;
  readonly jobs: JobsContract;
  readonly secrets: SecretsContract;
  readonly tenancy: TenancyContract;
}
