// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Use-cases. May import this context's domain and ports, and any allowed
// peer context's contracts/ (ADR M0.3 §1 domainDeps).
import type { ConversationsRepository } from "./ports/index.js";
import type { AgentsContract } from "@platos/context-agents/contracts/index.js";
import type { SkillsContract } from "@platos/context-skills/contracts/index.js";
import type { ToolsContract } from "@platos/context-tools/contracts/index.js";
import type { MemoryContract } from "@platos/context-memory/contracts/index.js";
import type { ProvidersContract } from "@platos/context-providers/contracts/index.js";
import type { FilesContract } from "@platos/context-files/contracts/index.js";
import type { CostMonitoringContract } from "@platos/context-cost-monitoring/contracts/index.js";
import type { JobsContract } from "@platos/context-jobs/contracts/index.js";
import type { SecretsContract } from "@platos/context-secrets/contracts/index.js";
import type { TenancyContract } from "@platos/context-tenancy/contracts/index.js";

export interface ConversationsUseCases {
  readonly repository: ConversationsRepository;
  readonly agents: AgentsContract;
  readonly skills: SkillsContract;
  readonly tools: ToolsContract;
  readonly memory: MemoryContract;
  readonly providers: ProvidersContract;
  readonly files: FilesContract;
  readonly costMonitoring: CostMonitoringContract;
  readonly jobs: JobsContract;
  readonly secrets: SecretsContract;
  readonly tenancy: TenancyContract;
}
