// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { ToolsAggregate } from "../domain/index.js";

export interface ToolsContract {
  readonly name: "tools";
  describe(id: string): Promise<ToolsAggregate | null>;
}
