// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { SecretsAggregate } from "../domain/index.js";

export interface SecretsContract {
  readonly name: "secrets";
  describe(id: string): Promise<SecretsAggregate | null>;
}
