#!/bin/sh
set -e

echo "========================================="
echo "  Platos Agent — Starting"
echo "========================================="

# Apply standalone SQL to create Platos tables (idempotent — uses IF NOT EXISTS)
if [ -f ./prisma-init.sql ]; then
  node -e "
    const { Client } = require('pg');
    const fs = require('fs');
    (async () => {
      const client = new Client({ connectionString: process.env.DATABASE_URL });
      await client.connect();
      const sql = fs.readFileSync('./prisma-init.sql', 'utf-8');
      await client.query(sql);
      await client.end();
      console.log('  Database tables ready');
    })().catch(e => console.log('  DB init:', e.message));
  " 2>/dev/null || echo "  DB init skipped"
fi

# The package deploy must carry the client generated by the clean control
# schema. Never generate a second client from a runtime fallback schema.
if [ ! -f ./node_modules/@platos/database/generated/control/index.js ]; then
  echo "  Missing deployed @platos/database generated/control client" >&2
  exit 1
fi

# Worker mode: WORKER_MODE=true runs the trigger.dev task worker instead of
# the NestJS HTTP server. Both use the same compiled bundle — the worker
# registers the tasks in src/trigger-tasks/ with the webapp's run engine.
if [ "${WORKER_MODE:-false}" = "true" ]; then
  echo "[1/1] Starting trigger.dev task worker (WORKER_MODE=true)..."
  exec node dist/trigger-worker.js
fi

echo "[1/2] Initializing database..."
echo "[2/2] Starting agent service..."
exec node dist/main.js
