#!/usr/bin/env bash
set -euo pipefail

candidate_dir="${1:?candidate artifact directory is required}"
layout_dir="${2:?OCI layout directory is required}"
load_candidates="${3:-false}"

: "${PLATOS_CANDIDATE_SHA:?PLATOS_CANDIDATE_SHA is required to verify candidate revision labels}"
: "${GITHUB_REPOSITORY_OWNER:?GITHUB_REPOSITORY_OWNER is required}"

mkdir -p "$layout_dir"

for candidate in \
  "agent AGENT platos-agent" \
  "webapp WEBAPP platos-webapp" \
  "migrations MIGRATIONS platos-migrations"; do
  read -r name env_name repository_name <<<"$candidate"
  env_file="$candidate_dir/$name.env"
  archive="$candidate_dir/$name.oci.tar"
  test -s "$env_file"
  test -s "$archive"
  # The env file is generated by the trusted workflow from fixed matrix values.
  # shellcheck disable=SC1090
  source "$env_file"

  identity_variable="WIN235_${env_name}_IMAGE"
  archive_sha_variable="WIN235_${env_name}_ARCHIVE_SHA256"
  identity="${!identity_variable}"
  expected_archive_sha="${!archive_sha_variable}"
  expected_repository="ghcr.io/${GITHUB_REPOSITORY_OWNER}/${repository_name}"
  expected_digest="${identity##*@}"

  test "$identity" = "${expected_repository}@${expected_digest}"
  [[ "$expected_digest" =~ ^sha256:[a-f0-9]{64}$ ]]
  [[ "$expected_archive_sha" =~ ^[a-f0-9]{64}$ ]]
  printf '%s  %s\n' "$expected_archive_sha" "$archive" | sha256sum --check --status

  candidate_layout="$layout_dir/$name"
  rm -rf "$candidate_layout"
  layout_ref="ocidir://${candidate_layout}:candidate"
  regctl image import "$layout_ref" "$archive"
  actual_digest="$(regctl image digest "$layout_ref")"
  test "$actual_digest" = "$expected_digest"
  revision="$(
    regctl image inspect --platform linux/amd64 "$layout_ref" \
      --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}'
  )"
  test "$revision" = "$PLATOS_CANDIDATE_SHA"

  if [ "$load_candidates" = "true" ]; then
    runtime_ref="win235.local/${repository_name}:sha256-${expected_digest#sha256:}"
    docker_archive="$layout_dir/$name.docker.tar"
    regctl image export --platform linux/amd64 --name "$runtime_ref" "$layout_ref" "$docker_archive"
    docker load --input "$docker_archive"
    loaded_revision="$(
      docker image inspect --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}' \
        "$runtime_ref"
    )"
    test "$loaded_revision" = "$PLATOS_CANDIDATE_SHA"
    printf 'WIN235_%s_RUNTIME_IMAGE=%s\n' "$env_name" "$runtime_ref" >>"$GITHUB_ENV"
    rm -f "$docker_archive"
  fi

  printf 'WIN235_%s_IMAGE=%s\n' "$env_name" "$identity" >>"$GITHUB_ENV"
  printf 'WIN235_%s_ARCHIVE_SHA256=%s\n' "$env_name" "$expected_archive_sha" >>"$GITHUB_ENV"
done
