// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Thin rest transport. Calls context use-cases only.
import type { AppModule } from "../../app.module.js";

export interface RestTransport {
  readonly kind: "rest";
  readonly app: AppModule;
}
