// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single ModelRouter implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { ModelRouter } from "@platos/kernel";

export interface ModelRouterProvidersAdapter extends ModelRouter {
  readonly adapterName: "model-router-providers";
}
