/** Exact pg_indexes inventory after replaying all 849 inherited migrations. */
export const legacyIndexCatalog = [
  { name: "BackgroundWorkerFile_friendlyId_key", table: "BackgroundWorkerFile" },
  { name: "BackgroundWorkerFile_pkey", table: "BackgroundWorkerFile" },
  { name: "BackgroundWorkerFile_projectId_contentHash_key", table: "BackgroundWorkerFile" },
  { name: "BackgroundWorkerTask_friendlyId_key", table: "BackgroundWorkerTask" },
  { name: "BackgroundWorkerTask_pkey", table: "BackgroundWorkerTask" },
  { name: "BackgroundWorkerTask_projectId_slug_idx", table: "BackgroundWorkerTask" },
  {
    name: "BackgroundWorkerTask_runtimeEnvironmentId_projectId_idx",
    table: "BackgroundWorkerTask",
  },
  { name: "BackgroundWorkerTask_workerId_slug_key", table: "BackgroundWorkerTask" },
  { name: "BackgroundWorker_friendlyId_key", table: "BackgroundWorker" },
  { name: "BackgroundWorker_pkey", table: "BackgroundWorker" },
  {
    name: "BackgroundWorker_projectId_runtimeEnvironmentId_version_key",
    table: "BackgroundWorker",
  },
  { name: "BackgroundWorker_runtimeEnvironmentId_createdAt_idx", table: "BackgroundWorker" },
  { name: "BackgroundWorker_runtimeEnvironmentId_idx", table: "BackgroundWorker" },
  { name: "BatchTaskRunError_batchTaskRunId_idx", table: "BatchTaskRunError" },
  { name: "BatchTaskRunError_batchTaskRunId_index_key", table: "BatchTaskRunError" },
  { name: "BatchTaskRunError_pkey", table: "BatchTaskRunError" },
  { name: "BatchTaskRunItem_batchTaskRunId_taskRunId_key", table: "BatchTaskRunItem" },
  { name: "BatchTaskRunItem_pkey", table: "BatchTaskRunItem" },
  { name: "BatchTaskRun_checkpointEventId_key", table: "BatchTaskRun" },
  { name: "BatchTaskRun_dependentTaskAttemptId_idx", table: "BatchTaskRun" },
  { name: "BatchTaskRun_friendlyId_key", table: "BatchTaskRun" },
  { name: "BatchTaskRun_oneTimeUseToken_key", table: "BatchTaskRun" },
  { name: "BatchTaskRun_pkey", table: "BatchTaskRun" },
  { name: "BatchTaskRun_runtimeEnvironmentId_id_idx", table: "BatchTaskRun" },
  { name: "BatchTaskRun_runtimeEnvironmentId_idempotencyKey_key", table: "BatchTaskRun" },
  { name: "BulkActionGroup_environmentId_createdAt_idx", table: "BulkActionGroup" },
  { name: "BulkActionGroup_friendlyId_key", table: "BulkActionGroup" },
  { name: "BulkActionGroup_pkey", table: "BulkActionGroup" },
  { name: "BulkActionItem_pkey", table: "BulkActionItem" },
  { name: "CheckpointRestoreEvent_checkpointId_idx", table: "CheckpointRestoreEvent" },
  { name: "CheckpointRestoreEvent_pkey", table: "CheckpointRestoreEvent" },
  { name: "CheckpointRestoreEvent_runId_idx", table: "CheckpointRestoreEvent" },
  { name: "Checkpoint_attemptId_idx", table: "Checkpoint" },
  { name: "Checkpoint_friendlyId_key", table: "Checkpoint" },
  { name: "Checkpoint_pkey", table: "Checkpoint" },
  { name: "Checkpoint_runId_idx", table: "Checkpoint" },
  { name: "ConnectedGithubRepository_pkey", table: "ConnectedGithubRepository" },
  { name: "ConnectedGithubRepository_projectId_key", table: "ConnectedGithubRepository" },
  { name: "ConnectedGithubRepository_repositoryId_idx", table: "ConnectedGithubRepository" },
  { name: "CustomerQuery_createdAt_idx", table: "CustomerQuery" },
  { name: "CustomerQuery_organizationId_createdAt_idx", table: "CustomerQuery" },
  { name: "CustomerQuery_pkey", table: "CustomerQuery" },
  { name: "DataMigration_name_key", table: "DataMigration" },
  { name: "DataMigration_pkey", table: "DataMigration" },
  { name: "EnvironmentVariableValue_pkey", table: "EnvironmentVariableValue" },
  {
    name: "EnvironmentVariableValue_variableId_environmentId_key",
    table: "EnvironmentVariableValue",
  },
  { name: "EnvironmentVariable_friendlyId_key", table: "EnvironmentVariable" },
  { name: "EnvironmentVariable_pkey", table: "EnvironmentVariable" },
  { name: "EnvironmentVariable_projectId_key_key", table: "EnvironmentVariable" },
  { name: "ErrorGroupState_environmentId_status_idx", table: "ErrorGroupState" },
  {
    name: "ErrorGroupState_environmentId_taskIdentifier_errorFingerpri_key",
    table: "ErrorGroupState",
  },
  { name: "ErrorGroupState_pkey", table: "ErrorGroupState" },
  { name: "FeatureFlag_key_key", table: "FeatureFlag" },
  { name: "FeatureFlag_pkey", table: "FeatureFlag" },
  { name: "GithubAppInstallation_appInstallationId_key", table: "GithubAppInstallation" },
  { name: "GithubAppInstallation_organizationId_idx", table: "GithubAppInstallation" },
  { name: "GithubAppInstallation_pkey", table: "GithubAppInstallation" },
  { name: "GithubRepository_installationId_githubId_key", table: "GithubRepository" },
  { name: "GithubRepository_installationId_idx", table: "GithubRepository" },
  { name: "GithubRepository_pkey", table: "GithubRepository" },
  { name: "ImpersonationAuditLog_adminId_idx", table: "ImpersonationAuditLog" },
  { name: "ImpersonationAuditLog_createdAt_idx", table: "ImpersonationAuditLog" },
  { name: "ImpersonationAuditLog_pkey", table: "ImpersonationAuditLog" },
  { name: "ImpersonationAuditLog_targetId_idx", table: "ImpersonationAuditLog" },
  { name: "IntegrationDeployment_commitSHA_idx", table: "IntegrationDeployment" },
  { name: "IntegrationDeployment_deploymentId_idx", table: "IntegrationDeployment" },
  { name: "IntegrationDeployment_pkey", table: "IntegrationDeployment" },
  { name: "InvitationCode_code_key", table: "InvitationCode" },
  { name: "InvitationCode_pkey", table: "InvitationCode" },
  { name: "MetricsDashboard_friendlyId_key", table: "MetricsDashboard" },
  { name: "MetricsDashboard_pkey", table: "MetricsDashboard" },
  { name: "MetricsDashboard_projectId_createdAt_idx", table: "MetricsDashboard" },
  { name: "MfaBackupCode_pkey", table: "MfaBackupCode" },
  { name: "MfaBackupCode_userId_code_key", table: "MfaBackupCode" },
  { name: "OrgMemberInvite_organizationId_email_key", table: "OrgMemberInvite" },
  { name: "OrgMemberInvite_pkey", table: "OrgMemberInvite" },
  { name: "OrgMemberInvite_token_key", table: "OrgMemberInvite" },
  { name: "OrgMember_organizationId_userId_key", table: "OrgMember" },
  { name: "OrgMember_pkey", table: "OrgMember" },
  { name: "OrganizationAccessToken_hashedToken_key", table: "OrganizationAccessToken" },
  {
    name: "OrganizationAccessToken_organizationId_type_createdAt_idx",
    table: "OrganizationAccessToken",
  },
  { name: "OrganizationAccessToken_pkey", table: "OrganizationAccessToken" },
  { name: "OrganizationIntegration_externalOrganizationId_idx", table: "OrganizationIntegration" },
  { name: "OrganizationIntegration_friendlyId_key", table: "OrganizationIntegration" },
  { name: "OrganizationIntegration_pkey", table: "OrganizationIntegration" },
  {
    name: "OrganizationProjectIntegration_externalEntityId_idx",
    table: "OrganizationProjectIntegration",
  },
  { name: "OrganizationProjectIntegration_pkey", table: "OrganizationProjectIntegration" },
  { name: "OrganizationProjectIntegration_projectId_idx", table: "OrganizationProjectIntegration" },
  {
    name: "OrganizationProjectIntegration_projectId_organizationIntegr_idx",
    table: "OrganizationProjectIntegration",
  },
  { name: "Organization_pkey", table: "Organization" },
  { name: "Organization_slug_key", table: "Organization" },
  {
    name: "PlatformNotificationInteraction_notificationId_userId_key",
    table: "PlatformNotificationInteraction",
  },
  { name: "PlatformNotificationInteraction_pkey", table: "PlatformNotificationInteraction" },
  { name: "PlatformNotification_friendlyId_key", table: "PlatformNotification" },
  { name: "PlatformNotification_pkey", table: "PlatformNotification" },
  { name: "PlatformNotification_surface_scope_startsAt_idx", table: "PlatformNotification" },
  { name: "PlatosAccessKey_pkey", table: "PlatosAccessKey" },
  { name: "PlatosAdminAudit_pkey", table: "PlatosAdminAudit" },
  { name: "PlatosAgentApproval_pkey", table: "PlatosAgentApproval" },
  { name: "PlatosAgentApproval_scope_agentId_idx", table: "PlatosAgentApproval" },
  { name: "PlatosAgentApproval_scope_approvalId_key", table: "PlatosAgentApproval" },
  { name: "PlatosAgentApproval_scope_createdAt_idx", table: "PlatosAgentApproval" },
  { name: "PlatosAgentApproval_scope_status_createdAt_idx", table: "PlatosAgentApproval" },
  { name: "PlatosAgentApproval_scope_threadId_idx", table: "PlatosAgentApproval" },
  {
    name: "PlatosAgentArtifact_organizationId_projectId_environmentId_idx",
    table: "PlatosAgentArtifact",
  },
  { name: "PlatosAgentArtifact_pkey", table: "PlatosAgentArtifact" },
  { name: "PlatosAgentArtifact_threadId_artifactKey_idx", table: "PlatosAgentArtifact" },
  { name: "PlatosAgentArtifact_threadId_artifactKey_revision_key", table: "PlatosAgentArtifact" },
  { name: "PlatosAgentArtifact_threadId_createdAt_idx", table: "PlatosAgentArtifact" },
  {
    name: "PlatosAgentCluster_organizationId_projectId_environmentId_idx",
    table: "PlatosAgentCluster",
  },
  { name: "PlatosAgentCluster_pkey", table: "PlatosAgentCluster" },
  { name: "PlatosAgentCluster_projectId_environmentId_slug_key", table: "PlatosAgentCluster" },
  { name: "PlatosAgentEval_pkey", table: "PlatosAgentEval" },
  { name: "PlatosAgentEval_runId_idx", table: "PlatosAgentEval" },
  { name: "PlatosAgentEval_scope_agent_createdAt_idx", table: "PlatosAgentEval" },
  { name: "PlatosAgentEval_scope_criterion_idx", table: "PlatosAgentEval" },
  { name: "PlatosAgentEval_scope_version_idx", table: "PlatosAgentEval" },
  { name: "PlatosAgentEval_threadId_idx", table: "PlatosAgentEval" },
  { name: "PlatosAgentMessage_editParentMessageId_idx", table: "PlatosAgentMessage" },
  { name: "PlatosAgentMessage_pkey", table: "PlatosAgentMessage" },
  { name: "PlatosAgentMessage_threadId_createdAt_idx", table: "PlatosAgentMessage" },
  { name: "PlatosAgentMessage_threadId_status_idx", table: "PlatosAgentMessage" },
  { name: "PlatosAgentMessage_threadId_threadReplyToId_idx", table: "PlatosAgentMessage" },
  { name: "PlatosAgentSkill_agentId_skillId_key", table: "PlatosAgentSkill" },
  {
    name: "PlatosAgentSkill_organizationId_projectId_environmentId_idx",
    table: "PlatosAgentSkill",
  },
  { name: "PlatosAgentSkill_pkey", table: "PlatosAgentSkill" },
  { name: "PlatosAgentSkill_skillId_idx", table: "PlatosAgentSkill" },
  { name: "PlatosAgentThread_agentId_idx", table: "PlatosAgentThread" },
  { name: "PlatosAgentThread_clusteringId_userId_idx", table: "PlatosAgentThread" },
  { name: "PlatosAgentThread_env_status_idx", table: "PlatosAgentThread" },
  {
    name: "PlatosAgentThread_organizationId_projectId_environmentId_us_idx",
    table: "PlatosAgentThread",
  },
  { name: "PlatosAgentThread_parentThreadId_idx", table: "PlatosAgentThread" },
  { name: "PlatosAgentThread_pkey", table: "PlatosAgentThread" },
  { name: "PlatosAgentVersion_agentId_idx", table: "PlatosAgentVersion" },
  { name: "PlatosAgentVersion_agentId_versionNumber_key", table: "PlatosAgentVersion" },
  { name: "PlatosAgentVersion_pkey", table: "PlatosAgentVersion" },
  { name: "PlatosAgent_clusteringId_idx", table: "PlatosAgent" },
  { name: "PlatosAgent_organizationId_projectId_environmentId_idx", table: "PlatosAgent" },
  { name: "PlatosAgent_pkey", table: "PlatosAgent" },
  { name: "PlatosAgent_projectId_environmentId_idx", table: "PlatosAgent" },
  { name: "PlatosAgent_projectId_environmentId_slug_key", table: "PlatosAgent" },
  { name: "PlatosBudgetCap_pkey", table: "PlatosBudgetCap" },
  { name: "PlatosBudgetCap_scope_idx", table: "PlatosBudgetCap" },
  { name: "PlatosBudgetCap_scope_scopeType_idx", table: "PlatosBudgetCap" },
  { name: "PlatosBudgetCap_scope_target_period_key", table: "PlatosBudgetCap" },
  {
    name: "PlatosChannelAppThread_installationId_channelThreadKey_key",
    table: "PlatosChannelAppThread",
  },
  { name: "PlatosChannelAppThread_pkey", table: "PlatosChannelAppThread" },
  { name: "PlatosChannelAppThread_platosThreadId_idx", table: "PlatosChannelAppThread" },
  {
    name: "PlatosChannelApp_organizationId_projectId_environmentId_pro_idx",
    table: "PlatosChannelApp",
  },
  { name: "PlatosChannelApp_pkey", table: "PlatosChannelApp" },
  { name: "PlatosChannelConnection_agentId_idx", table: "PlatosChannelConnection" },
  {
    name: "PlatosChannelConnection_organizationId_projectId_environmen_idx",
    table: "PlatosChannelConnection",
  },
  { name: "PlatosChannelConnection_pkey", table: "PlatosChannelConnection" },
  { name: "PlatosChannelInstallation_appId_status_idx", table: "PlatosChannelInstallation" },
  {
    name: "PlatosChannelInstallation_appId_teamId_enterpriseId_key",
    table: "PlatosChannelInstallation",
  },
  { name: "PlatosChannelInstallation_pkey", table: "PlatosChannelInstallation" },
  { name: "PlatosChannelThread_agentId_idx", table: "PlatosChannelThread" },
  { name: "PlatosChannelThread_connectionId_channelThreadKey_key", table: "PlatosChannelThread" },
  { name: "PlatosChannelThread_pkey", table: "PlatosChannelThread" },
  { name: "PlatosChannelThread_platosThreadId_idx", table: "PlatosChannelThread" },
  {
    name: "PlatosConnectedEntity_organizationId_projectId_entityId_key",
    table: "PlatosConnectedEntity",
  },
  { name: "PlatosConnectedEntity_organizationId_projectId_idx", table: "PlatosConnectedEntity" },
  { name: "PlatosConnectedEntity_pkey", table: "PlatosConnectedEntity" },
  { name: "PlatosCredentialAudit_pkey", table: "PlatosCredentialAudit" },
  {
    name: "PlatosEndUserIdentity_organizationId_projectId_environmentI_key",
    table: "PlatosEndUserIdentity",
  },
  { name: "PlatosEndUserIdentity_pkey", table: "PlatosEndUserIdentity" },
  { name: "PlatosEndUserIdentity_platosEndUserId_idx", table: "PlatosEndUserIdentity" },
  { name: "PlatosEndUser_pkey", table: "PlatosEndUser" },
  { name: "PlatosEntityMcpClient_pkey", table: "PlatosEntityMcpClient" },
  { name: "PlatosEntityMcpConfig_enabled_idx", table: "PlatosEntityMcpConfig" },
  { name: "PlatosEntityMcpConfig_pkey", table: "PlatosEntityMcpConfig" },
  { name: "PlatosEntityMcpToolAcl_entityPk_exposed_idx", table: "PlatosEntityMcpToolAcl" },
  { name: "PlatosEntityMcpToolAcl_entityPk_toolId_key", table: "PlatosEntityMcpToolAcl" },
  { name: "PlatosEntityMcpToolAcl_pkey", table: "PlatosEntityMcpToolAcl" },
  {
    name: "PlatosEntityToolMapping_entityId_environmentId_enabled_idx",
    table: "PlatosEntityToolMapping",
  },
  { name: "PlatosEntityToolMapping_pkey", table: "PlatosEntityToolMapping" },
  {
    name: "PlatosEntityToolMapping_toolId_entityId_environmentId_key",
    table: "PlatosEntityToolMapping",
  },
  { name: "PlatosErasureOperation_organizationId_status_idx", table: "PlatosErasureOperation" },
  { name: "PlatosErasureOperation_pkey", table: "PlatosErasureOperation" },
  { name: "PlatosErasureOperation_status_requestedAt_idx", table: "PlatosErasureOperation" },
  { name: "PlatosErasureOperation_subjectKeyHash_idx", table: "PlatosErasureOperation" },
  { name: "PlatosEvalCriterion_pkey", table: "PlatosEvalCriterion" },
  { name: "PlatosEvalCriterion_scope_agentId_idx", table: "PlatosEvalCriterion" },
  { name: "PlatosEvalCriterion_scope_idx", table: "PlatosEvalCriterion" },
  { name: "PlatosEvent_pkey", table: "PlatosEvent" },
  { name: "PlatosGoldenSet_pkey", table: "PlatosGoldenSet" },
  { name: "PlatosGoldenSet_scope_agentId_idx", table: "PlatosGoldenSet" },
  { name: "PlatosMCPToken_pkey", table: "PlatosMCPToken" },
  { name: "PlatosMCPToken_tokenHash_key", table: "PlatosMCPToken" },
  { name: "PlatosMacro_pkey", table: "PlatosMacro" },
  { name: "PlatosMcpAnonSession_mcpUserId_key", table: "PlatosMcpAnonSession" },
  { name: "PlatosMcpAnonSession_pkey", table: "PlatosMcpAnonSession" },
  { name: "PlatosMcpBearerToken_pkey", table: "PlatosMcpBearerToken" },
  { name: "PlatosMcpBearerToken_tokenHash_key", table: "PlatosMcpBearerToken" },
  { name: "PlatosMcpOidcSession_mcpUserId_key", table: "PlatosMcpOidcSession" },
  { name: "PlatosMcpOidcSession_pkey", table: "PlatosMcpOidcSession" },
  { name: "PlatosMemoryEntity_pkey", table: "PlatosMemoryEntity" },
  { name: "PlatosMemoryRelationship_pkey", table: "PlatosMemoryRelationship" },
  { name: "PlatosMemory_archivedAt_idx", table: "PlatosMemory" },
  { name: "PlatosMemory_pkey", table: "PlatosMemory" },
  { name: "PlatosMessageAttachment_expiresAt_idx", table: "PlatosMessageAttachment" },
  { name: "PlatosMessageAttachment_messageId_idx", table: "PlatosMessageAttachment" },
  {
    name: "PlatosMessageAttachment_organizationId_projectId_environmen_idx",
    table: "PlatosMessageAttachment",
  },
  { name: "PlatosMessageAttachment_pkey", table: "PlatosMessageAttachment" },
  { name: "PlatosMessageAttachment_uploadedBy_idx", table: "PlatosMessageAttachment" },
  { name: "PlatosMessageRating_messageId_userId_key", table: "PlatosMessageRating" },
  { name: "PlatosMessageRating_pkey", table: "PlatosMessageRating" },
  { name: "PlatosMessageRating_scope_agentId_idx", table: "PlatosMessageRating" },
  { name: "PlatosMessageRating_scope_agentVersionId_idx", table: "PlatosMessageRating" },
  { name: "PlatosMessageRating_threadId_idx", table: "PlatosMessageRating" },
  { name: "PlatosNotificationRule_pkey", table: "PlatosNotificationRule" },
  { name: "PlatosOAuthAccessToken_pkey", table: "PlatosOAuthAccessToken" },
  { name: "PlatosOAuthAuthCode_pkey", table: "PlatosOAuthAuthCode" },
  { name: "PlatosOAuthClient_clientId_key", table: "PlatosOAuthClient" },
  { name: "PlatosOAuthClient_pkey", table: "PlatosOAuthClient" },
  { name: "PlatosOAuthRefreshToken_pkey", table: "PlatosOAuthRefreshToken" },
  { name: "PlatosOrgMcpPolicy_pkey", table: "PlatosOrgMcpPolicy" },
  { name: "PlatosPAT_pkey", table: "PlatosPAT" },
  { name: "PlatosPAT_tokenHash_key", table: "PlatosPAT" },
  { name: "PlatosPostmanTemplate_pkey", table: "PlatosPostmanTemplate" },
  {
    name: "PlatosProviderEnabled_organizationId_projectId_environmentI_idx",
    table: "PlatosProviderEnabled",
  },
  {
    name: "PlatosProviderEnabled_organizationId_projectId_environmentI_key",
    table: "PlatosProviderEnabled",
  },
  { name: "PlatosProviderEnabled_pkey", table: "PlatosProviderEnabled" },
  { name: "PlatosProviderKey_orgProjEnvProviderEnvVar_key", table: "PlatosProviderKey" },
  { name: "PlatosProviderKey_orgProjEnv_isDefault_idx", table: "PlatosProviderKey" },
  { name: "PlatosProviderKey_orgProjEnv_provider_idx", table: "PlatosProviderKey" },
  { name: "PlatosProviderKey_pkey", table: "PlatosProviderKey" },
  { name: "PlatosSafetyEvent_pkey", table: "PlatosSafetyEvent" },
  { name: "PlatosSafetyEvent_scope_agentId_idx", table: "PlatosSafetyEvent" },
  { name: "PlatosSafetyEvent_scope_createdAt_idx", table: "PlatosSafetyEvent" },
  { name: "PlatosSafetyEvent_scope_detector_idx", table: "PlatosSafetyEvent" },
  { name: "PlatosSafetyEvent_scope_threadId_idx", table: "PlatosSafetyEvent" },
  { name: "PlatosSkill_isOfficial_idx", table: "PlatosSkill" },
  { name: "PlatosSkill_organizationId_projectId_environmentId_idx", table: "PlatosSkill" },
  { name: "PlatosSkill_organizationId_projectId_environmentId_skillId_key", table: "PlatosSkill" },
  { name: "PlatosSkill_pkey", table: "PlatosSkill" },
  { name: "PlatosSkill_skillId_idx", table: "PlatosSkill" },
  { name: "PlatosTask_orgProjEnvTaskId_key", table: "PlatosTask" },
  { name: "PlatosTask_orgProjEnv_idx", table: "PlatosTask" },
  { name: "PlatosTask_pkey", table: "PlatosTask" },
  { name: "PlatosTask_triggerType_isActive_idx", table: "PlatosTask" },
  { name: "PlatosToolCallAudit_pkey", table: "PlatosToolCallAudit" },
  { name: "PlatosToolCallAudit_scope_agentId_idx", table: "PlatosToolCallAudit" },
  { name: "PlatosToolCallAudit_scope_createdAt_idx", table: "PlatosToolCallAudit" },
  { name: "PlatosToolCallAudit_scope_status_idx", table: "PlatosToolCallAudit" },
  { name: "PlatosToolCallAudit_scope_threadId_idx", table: "PlatosToolCallAudit" },
  { name: "PlatosToolCallAudit_scope_toolName_idx", table: "PlatosToolCallAudit" },
  { name: "PlatosToolDefinition_category_idx", table: "PlatosToolDefinition" },
  { name: "PlatosToolDefinition_organizationId_projectId_idx", table: "PlatosToolDefinition" },
  { name: "PlatosToolDefinition_organizationId_projectId_name_key", table: "PlatosToolDefinition" },
  { name: "PlatosToolDefinition_pkey", table: "PlatosToolDefinition" },
  { name: "PlatosToolHealth_entityId_environmentId_idx", table: "PlatosToolHealth" },
  { name: "PlatosToolHealth_pkey", table: "PlatosToolHealth" },
  { name: "PlatosToolHealth_toolId_entityId_environmentId_key", table: "PlatosToolHealth" },
  { name: "ProjectAlertChannel_friendlyId_key", table: "ProjectAlertChannel" },
  { name: "ProjectAlertChannel_pkey", table: "ProjectAlertChannel" },
  { name: "ProjectAlertChannel_projectId_deduplicationKey_key", table: "ProjectAlertChannel" },
  {
    name: "ProjectAlertStorage_alertChannelId_alertType_storageId_idx",
    table: "ProjectAlertStorage",
  },
  { name: "ProjectAlertStorage_pkey", table: "ProjectAlertStorage" },
  { name: "ProjectAlert_friendlyId_key", table: "ProjectAlert" },
  { name: "ProjectAlert_pkey", table: "ProjectAlert" },
  { name: "Project_externalRef_key", table: "Project" },
  { name: "Project_pkey", table: "Project" },
  { name: "Project_slug_key", table: "Project" },
  { name: "RealtimeStreamChunk_createdAt_idx", table: "RealtimeStreamChunk" },
  { name: "RealtimeStreamChunk_pkey", table: "RealtimeStreamChunk" },
  { name: "RealtimeStreamChunk_runId_idx", table: "RealtimeStreamChunk" },
  { name: "RuntimeEnvironmentSession_pkey", table: "RuntimeEnvironmentSession" },
  { name: "RuntimeEnvironment_apiKey_key", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_organizationId_idx", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_parentEnvironmentId_idx", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_pkApiKey_key", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_pkey", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_projectId_idx", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_projectId_shortcode_key", table: "RuntimeEnvironment" },
  { name: "RuntimeEnvironment_projectId_slug_orgMemberId_key", table: "RuntimeEnvironment" },
  { name: "SecretReference_key_key", table: "SecretReference" },
  { name: "SecretReference_pkey", table: "SecretReference" },
  { name: "SecretStore_key_idx", table: "SecretStore" },
  { name: "SecretStore_key_key", table: "SecretStore" },
  { name: "TaskEventPartitioned_pkey", table: "TaskEventPartitioned" },
  { name: "TaskEventPartitioned_runId_idx", table: "TaskEventPartitioned" },
  { name: "TaskEventPartitioned_spanId_idx", table: "TaskEventPartitioned" },
  { name: "TaskEventPartitioned_traceId_idx", table: "TaskEventPartitioned" },
  { name: "TaskEvent_pkey", table: "TaskEvent" },
  { name: "TaskEvent_runId_idx", table: "TaskEvent" },
  { name: "TaskEvent_spanId_idx", table: "TaskEvent" },
  { name: "TaskEvent_traceId_idx", table: "TaskEvent" },
  { name: "TaskQueue_friendlyId_key", table: "TaskQueue" },
  { name: "TaskQueue_pkey", table: "TaskQueue" },
  { name: "TaskQueue_runtimeEnvironmentId_name_key", table: "TaskQueue" },
  { name: "TaskRunAttempt_friendlyId_key", table: "TaskRunAttempt" },
  { name: "TaskRunAttempt_pkey", table: "TaskRunAttempt" },
  { name: "TaskRunAttempt_taskRunId_idx", table: "TaskRunAttempt" },
  { name: "TaskRunAttempt_taskRunId_number_key", table: "TaskRunAttempt" },
  { name: "TaskRunCheckpoint_friendlyId_key", table: "TaskRunCheckpoint" },
  { name: "TaskRunCheckpoint_pkey", table: "TaskRunCheckpoint" },
  { name: "TaskRunCounter_pkey", table: "TaskRunCounter" },
  { name: "TaskRunDependency_checkpointEventId_key", table: "TaskRunDependency" },
  { name: "TaskRunDependency_dependentAttemptId_idx", table: "TaskRunDependency" },
  { name: "TaskRunDependency_dependentBatchRunId_idx", table: "TaskRunDependency" },
  { name: "TaskRunDependency_pkey", table: "TaskRunDependency" },
  { name: "TaskRunDependency_taskRunId_key", table: "TaskRunDependency" },
  { name: "TaskRunExecutionSnapshot_pkey", table: "TaskRunExecutionSnapshot" },
  {
    name: "TaskRunExecutionSnapshot_runId_isValid_createdAt_idx",
    table: "TaskRunExecutionSnapshot",
  },
  { name: "TaskRunNumberCounter_pkey", table: "TaskRunNumberCounter" },
  { name: "TaskRunNumberCounter_taskIdentifier_environmentId_key", table: "TaskRunNumberCounter" },
  { name: "TaskRunTag_friendlyId_key", table: "TaskRunTag" },
  { name: "TaskRunTag_name_id_idx", table: "TaskRunTag" },
  { name: "TaskRunTag_pkey", table: "TaskRunTag" },
  { name: "TaskRunTag_projectId_name_key", table: "TaskRunTag" },
  { name: "TaskRunTemplate_pkey", table: "TaskRunTemplate" },
  {
    name: "TaskRunTemplate_projectId_taskSlug_triggerSource_createdAt_idx",
    table: "TaskRunTemplate",
  },
  { name: "TaskRunWaitpoint_pkey", table: "TaskRunWaitpoint" },
  { name: "TaskRunWaitpoint_taskRunId_idx", table: "TaskRunWaitpoint" },
  { name: "TaskRunWaitpoint_taskRunId_waitpointId_batchIndex_key", table: "TaskRunWaitpoint" },
  { name: "TaskRunWaitpoint_taskRunId_waitpointId_batchIndex_null_key", table: "TaskRunWaitpoint" },
  { name: "TaskRunWaitpoint_waitpointId_idx", table: "TaskRunWaitpoint" },
  { name: "TaskRun_createdAt_idx", table: "TaskRun" },
  { name: "TaskRun_friendlyId_key", table: "TaskRun" },
  { name: "TaskRun_oneTimeUseToken_key", table: "TaskRun" },
  { name: "TaskRun_parentSpanId_idx", table: "TaskRun" },
  { name: "TaskRun_parentTaskRunId_idx", table: "TaskRun" },
  { name: "TaskRun_pkey", table: "TaskRun" },
  { name: "TaskRun_runTags_idx", table: "TaskRun" },
  { name: "TaskRun_runtimeEnvironmentId_batchId_idx", table: "TaskRun" },
  { name: "TaskRun_runtimeEnvironmentId_createdAt_idx", table: "TaskRun" },
  { name: "TaskRun_runtimeEnvironmentId_taskIdentifier_idempotencyKey_key", table: "TaskRun" },
  { name: "TaskRun_scheduleId_createdAt_idx", table: "TaskRun" },
  { name: "TaskRun_spanId_idx", table: "TaskRun" },
  { name: "TaskRun_status_runtimeEnvironmentId_createdAt_id_idx", table: "TaskRun" },
  { name: "TaskScheduleInstance_environmentId_idx", table: "TaskScheduleInstance" },
  { name: "TaskScheduleInstance_pkey", table: "TaskScheduleInstance" },
  { name: "TaskScheduleInstance_projectId_active_idx", table: "TaskScheduleInstance" },
  { name: "TaskScheduleInstance_taskScheduleId_environmentId_key", table: "TaskScheduleInstance" },
  { name: "TaskSchedule_friendlyId_key", table: "TaskSchedule" },
  { name: "TaskSchedule_pkey", table: "TaskSchedule" },
  { name: "TaskSchedule_projectId_createdAt_idx", table: "TaskSchedule" },
  { name: "TaskSchedule_projectId_deduplicationKey_key", table: "TaskSchedule" },
  { name: "TaskSchedule_projectId_idx", table: "TaskSchedule" },
  { name: "User_authIdentifier_key", table: "User" },
  { name: "User_email_key", table: "User" },
  { name: "User_pkey", table: "User" },
  { name: "WaitpointTag_environmentId_name_key", table: "WaitpointTag" },
  { name: "WaitpointTag_pkey", table: "WaitpointTag" },
  { name: "Waitpoint_completedByBatchId_idx", table: "Waitpoint" },
  { name: "Waitpoint_completedByTaskRunId_key", table: "Waitpoint" },
  { name: "Waitpoint_environmentId_idempotencyKey_key", table: "Waitpoint" },
  { name: "Waitpoint_environmentId_type_createdAt_idx", table: "Waitpoint" },
  { name: "Waitpoint_environmentId_type_id_idx", table: "Waitpoint" },
  { name: "Waitpoint_environmentId_type_status_idx", table: "Waitpoint" },
  { name: "Waitpoint_friendlyId_key", table: "Waitpoint" },
  { name: "Waitpoint_pkey", table: "Waitpoint" },
  { name: "WorkerDeploymentPromotion_environmentId_label_key", table: "WorkerDeploymentPromotion" },
  { name: "WorkerDeploymentPromotion_pkey", table: "WorkerDeploymentPromotion" },
  { name: "WorkerDeployment_commitSHA_idx", table: "WorkerDeployment" },
  { name: "WorkerDeployment_environmentId_version_key", table: "WorkerDeployment" },
  { name: "WorkerDeployment_friendlyId_key", table: "WorkerDeployment" },
  { name: "WorkerDeployment_pkey", table: "WorkerDeployment" },
  { name: "WorkerDeployment_projectId_shortCode_key", table: "WorkerDeployment" },
  { name: "WorkerDeployment_workerId_key", table: "WorkerDeployment" },
  { name: "WorkerGroupToken_pkey", table: "WorkerGroupToken" },
  { name: "WorkerGroupToken_tokenHash_key", table: "WorkerGroupToken" },
  { name: "WorkerInstanceGroup_masterQueue_key", table: "WorkerInstanceGroup" },
  { name: "WorkerInstanceGroup_pkey", table: "WorkerInstanceGroup" },
  { name: "WorkerInstanceGroup_tokenId_key", table: "WorkerInstanceGroup" },
  { name: "WorkerInstance_pkey", table: "WorkerInstance" },
  { name: "WorkerInstance_workerGroupId_resourceIdentifier_key", table: "WorkerInstance" },
  {
    name: "_BackgroundWorkerToBackgroundWorkerFile_AB_pkey",
    table: "_BackgroundWorkerToBackgroundWorkerFile",
  },
  {
    name: "_BackgroundWorkerToBackgroundWorkerFile_B_index",
    table: "_BackgroundWorkerToBackgroundWorkerFile",
  },
  { name: "_BackgroundWorkerToTaskQueue_AB_pkey", table: "_BackgroundWorkerToTaskQueue" },
  { name: "_BackgroundWorkerToTaskQueue_B_index", table: "_BackgroundWorkerToTaskQueue" },
  { name: "_TaskRunToTaskRunTag_AB_pkey", table: "_TaskRunToTaskRunTag" },
  { name: "_TaskRunToTaskRunTag_B_index", table: "_TaskRunToTaskRunTag" },
  { name: "_WaitpointRunConnections_AB_pkey", table: "_WaitpointRunConnections" },
  { name: "_WaitpointRunConnections_B_index", table: "_WaitpointRunConnections" },
  { name: "_completedWaitpoints_AB_pkey", table: "_completedWaitpoints" },
  { name: "_completedWaitpoints_B_index", table: "_completedWaitpoints" },
  { name: "_prisma_migrations_pkey", table: "_prisma_migrations" },
  { name: "idx_batchtaskrunitem_taskrun", table: "BatchTaskRunItem" },
  { name: "idx_batchtaskrunitem_taskrunattempt", table: "BatchTaskRunItem" },
  { name: "llm_models_friendly_id_key", table: "llm_models" },
  { name: "llm_models_pkey", table: "llm_models" },
  { name: "llm_models_project_id_idx", table: "llm_models" },
  { name: "llm_models_project_id_model_name_start_date_key", table: "llm_models" },
  { name: "llm_prices_model_id_usage_type_pricing_tier_id_key", table: "llm_prices" },
  { name: "llm_prices_pkey", table: "llm_prices" },
  { name: "llm_pricing_tiers_model_id_name_key", table: "llm_pricing_tiers" },
  { name: "llm_pricing_tiers_model_id_priority_key", table: "llm_pricing_tiers" },
  { name: "llm_pricing_tiers_pkey", table: "llm_pricing_tiers" },
  { name: "platos_access_key_scope_idx", table: "PlatosAccessKey" },
  { name: "platos_access_key_scope_uniq", table: "PlatosAccessKey" },
  { name: "platos_admin_audit_scope_action_idx", table: "PlatosAdminAudit" },
  { name: "platos_admin_audit_scope_actor_idx", table: "PlatosAdminAudit" },
  { name: "platos_admin_audit_scope_createdAt_idx", table: "PlatosAdminAudit" },
  { name: "platos_admin_audit_scope_subject_idx", table: "PlatosAdminAudit" },
  { name: "platos_approval_scope_requestHash_idx", table: "PlatosAgentApproval" },
  { name: "platos_budget_cap_scope_period_tier_uk", table: "PlatosBudgetCap" },
  { name: "platos_credential_audit_actor_idx", table: "PlatosCredentialAudit" },
  { name: "platos_credential_audit_credential_idx", table: "PlatosCredentialAudit" },
  { name: "platos_credential_audit_scope_idx", table: "PlatosCredentialAudit" },
  { name: "platos_end_user_scope_ext_uniq", table: "PlatosEndUser" },
  { name: "platos_end_user_scope_last_active_idx", table: "PlatosEndUser" },
  { name: "platos_end_user_scope_linked_ext_uniq", table: "PlatosEndUser" },
  { name: "platos_erasure_operation_org_idempotency_key", table: "PlatosErasureOperation" },
  { name: "platos_event_scope_created_idx", table: "PlatosEvent" },
  { name: "platos_event_type_created_idx", table: "PlatosEvent" },
  { name: "platos_macro_creator_idx", table: "PlatosMacro" },
  { name: "platos_macro_scope_idx", table: "PlatosMacro" },
  { name: "platos_mcp_anon_entity_user_idx", table: "PlatosMcpAnonSession" },
  { name: "platos_mcp_bearer_entity_idx", table: "PlatosMcpBearerToken" },
  { name: "platos_mcp_bearer_hash_idx", table: "PlatosMcpBearerToken" },
  { name: "platos_mcp_oidc_entity_email_idx", table: "PlatosMcpOidcSession" },
  { name: "platos_mcp_oidc_entity_user_idx", table: "PlatosMcpOidcSession" },
  { name: "platos_mcp_policy_scope_idx", table: "PlatosOrgMcpPolicy" },
  { name: "platos_mcp_token_expires_idx", table: "PlatosMCPToken" },
  { name: "platos_mcp_token_scope_idx", table: "PlatosMCPToken" },
  { name: "platos_mem_dedup_uniq", table: "PlatosMemory" },
  { name: "platos_mem_embedding_hnsw", table: "PlatosMemory" },
  { name: "platos_mem_entity_scope_agent_idx", table: "PlatosMemoryEntity" },
  { name: "platos_mem_entity_scope_key_unq", table: "PlatosMemoryEntity" },
  { name: "platos_mem_entity_scope_type_idx", table: "PlatosMemoryEntity" },
  { name: "platos_mem_entity_scope_user_idx", table: "PlatosMemoryEntity" },
  { name: "platos_mem_rel_from_idx", table: "PlatosMemoryRelationship" },
  { name: "platos_mem_rel_scope_agent_idx", table: "PlatosMemoryRelationship" },
  { name: "platos_mem_rel_scope_type_idx", table: "PlatosMemoryRelationship" },
  { name: "platos_mem_rel_scope_user_idx", table: "PlatosMemoryRelationship" },
  { name: "platos_mem_rel_to_idx", table: "PlatosMemoryRelationship" },
  { name: "platos_mem_scope_agent_idx", table: "PlatosMemory" },
  { name: "platos_mem_scope_kind_idx", table: "PlatosMemory" },
  { name: "platos_mem_scope_user_confidence_idx", table: "PlatosMemory" },
  { name: "platos_mem_scope_user_idx", table: "PlatosMemory" },
  { name: "platos_mem_user_created_idx", table: "PlatosMemory" },
  { name: "platos_notification_rule_scope_idx", table: "PlatosNotificationRule" },
  { name: "platos_oauth_access_client_user_idx", table: "PlatosOAuthAccessToken" },
  { name: "platos_oauth_access_entity_idx", table: "PlatosOAuthAccessToken" },
  { name: "platos_oauth_access_expires_idx", table: "PlatosOAuthAccessToken" },
  { name: "platos_oauth_authcode_client_user_idx", table: "PlatosOAuthAuthCode" },
  { name: "platos_oauth_authcode_entity_idx", table: "PlatosOAuthAuthCode" },
  { name: "platos_oauth_authcode_expires_idx", table: "PlatosOAuthAuthCode" },
  { name: "platos_oauth_client_entity_idx", table: "PlatosOAuthClient" },
  { name: "platos_oauth_client_org_idx", table: "PlatosOAuthClient" },
  { name: "platos_oauth_refresh_client_user_idx", table: "PlatosOAuthRefreshToken" },
  { name: "platos_oauth_refresh_entity_idx", table: "PlatosOAuthRefreshToken" },
  { name: "platos_oauth_refresh_expires_idx", table: "PlatosOAuthRefreshToken" },
  { name: "platos_pat_token_hash_idx", table: "PlatosPAT" },
  { name: "platos_pat_user_idx", table: "PlatosPAT" },
  { name: "platos_postman_tmpl_scope_agent_idx", table: "PlatosPostmanTemplate" },
  { name: "platos_tool_audit_entity_source_idx", table: "PlatosToolCallAudit" },
  { name: "prompt_versions_contentHash_idx", table: "prompt_versions" },
  { name: "prompt_versions_pkey", table: "prompt_versions" },
  { name: "prompt_versions_promptId_idx", table: "prompt_versions" },
  { name: "prompt_versions_promptId_version_key", table: "prompt_versions" },
  { name: "prompts_friendly_id_key", table: "prompts" },
  { name: "prompts_pkey", table: "prompts" },
  { name: "prompts_projectId_idx", table: "prompts" },
  { name: "prompts_projectId_runtimeEnvironmentId_slug_key", table: "prompts" },
  { name: "prompts_runtimeEnvironmentId_idx", table: "prompts" },
] as const;
