// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single Cache implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { Cache } from "@platos/kernel";

export interface RedisCacheAdapter extends Cache {
  readonly adapterName: "redis-cache";
}
