// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { IdentityAccessAggregate } from "../domain/index.js";

export interface IdentityAccessContract {
  readonly name: "identity-access";
  describe(id: string): Promise<IdentityAccessAggregate | null>;
}
