// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// Stdio entry point. Reuses the tools context contract surface.
import type { ToolsContract } from "@platos/context-tools/contracts/index.js";

export type StdioBootstrap = () => Promise<ToolsContract>;
