// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The ONLY surface other contexts and apps/core-api may import.
import type { SkillsAggregate } from "../domain/index.js";

export interface SkillsContract {
  readonly name: "skills";
  describe(id: string): Promise<SkillsAggregate | null>;
}
