// PLACEHOLDER — generated by scripts/arch/gen-v1-skeleton.mjs. Do not edit by hand.
// The single ObservabilitySink implementation. The vendor client is imported
// HERE and nowhere else in the repository.
import type { ObservabilitySink } from "@platos/context-observability/application/ports/index.js";

export interface ClickhouseObservabilityAdapter extends ObservabilitySink {
  readonly adapterName: "clickhouse-observability";
}
