import { z } from "zod";

export type OrgForPath = { slug: string };
export type ProjectForPath = { slug: string };
export type EnvironmentForPath = { slug: string };
export const OrganizationParamsSchema = z.object({ organizationSlug: z.string().min(1) });
export const ProjectParamSchema = OrganizationParamsSchema.extend({ projectParam: z.string().min(1) });
export const EnvironmentParamSchema = ProjectParamSchema.extend({ envParam: z.string().min(1) });

export const rootPath = () => "/";
export const accountPath = () => "/account";
export const logoutPath = () => "/logout";
export const newOrganizationPath = () => "/orgs/new";
export const organizationPath = (o: OrgForPath) => `/orgs/${o.slug}`;
export const organizationSettingsPath = (o: OrgForPath) => `${organizationPath(o)}/settings`;
export const organizationTeamPath = (o: OrgForPath) => `${organizationPath(o)}/settings/team`;
export const newProjectPath = (o: OrgForPath) => `${organizationPath(o)}/projects/new`;
export const v3ProjectPath = (o: OrgForPath, p: ProjectForPath) => `${organizationPath(o)}/projects/${p.slug}`;
export const v3EnvironmentPath = (o: OrgForPath, p: ProjectForPath, e: EnvironmentForPath) => `${v3ProjectPath(o,p)}/env/${e.slug}`;
const envPath = v3EnvironmentPath;
export const agentsPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath) => `${envPath(o,p,e)}/agents`;
export const agentPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath,a:{id:string}) => `${agentsPath(o,p,e)}/${a.id}`;
export const agentChatPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath,a:{id:string}) => `${agentPath(o,p,e,a)}/chat`;
export const agentConversationsPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath,a:{id:string}) => `${agentPath(o,p,e,a)}/conversations`;
export const agentConversationPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath,a:{id:string},t:{id:string}) => `${agentConversationsPath(o,p,e,a)}/${t.id}`;
export const agentVersionsPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath,a:{id:string}) => `${agentPath(o,p,e,a)}/versions`;
export const agentCanaryPath = (o: OrgForPath,p: ProjectForPath,e: EnvironmentForPath,a:{id:string}) => `${agentPath(o,p,e,a)}/canary`;
const scoped = (name:string) => (o:OrgForPath,p:ProjectForPath,e:EnvironmentForPath) => `${envPath(o,p,e)}/${name}`;
export const agentToolsPath = scoped("agent-tools");
export const agentEntitiesPath = scoped("agent-entities");
export const agentAccountsPath = scoped("agent-accounts");
export const agentMonitoringPath = scoped("agent-monitoring");
export const agentClustersPath = scoped("agent-clusters");
export const agentMcpsPath = scoped("mcps");
export const agentFilesPath = scoped("files");
export const agentGovernancePath = scoped("agent-governance");
export const approvalsPath = scoped("approvals");
export const agentBudgetsPath = scoped("agent-budgets");
export const agentProvidersPath = scoped("agent-providers");
export const agentConnectPath = scoped("agent-connect");
export const agentEvalsPath = scoped("agent-evals");
export const evalCriteriaPath = scoped("eval-criteria");
export const skillsPath = scoped("skills");
export const memoriesPath = scoped("memories");
export const platosTasksPath = scoped("platos-tasks");
export const v3ApiKeysPath = scoped("apikeys");
export const v3EnvironmentVariablesPath = scoped("environment-variables");
export const v3ProjectSettingsGeneralPath = scoped("settings/general");
export const v3ProjectSettingsIntegrationsMcpPath = scoped("settings/integrations/mcp");
